name: Daily Altseason Analysis

on:
  schedule:
    - cron: "15 6 * * *"   # Daily at 06:15 UTC
  workflow_dispatch:        # Manual trigger

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Create reports directory
      run: mkdir -p reports
    
    - name: Run daily analysis
      run: python -m scripts.run_daily
    
    - name: Commit and push if changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add reports/ README.md
        git diff --staged --quiet || (git commit -m "chore: daily report $(date -u +%F)" && git push)
